import {describe, it, expect} from 'vitest'
import {toWord} from "../src/phonemes";

describe('toWord', () => {
  it('works with full wordlist', () => {
    expect(toWord('papagáj')).toEqual(['p', 'a', 'p', 'a', 'g', 'á', 'j'])
    expect(toWord('papuče')).toEqual(['p', 'a', 'p', 'u', 'č', 'e'])
    expect(toWord('pavúk')).toEqual(['p', 'a', 'v', 'ú', 'k'])
    expect(toWord('päť')).toEqual(['p', 'ä', 'ť'])
    expect(toWord('pes')).toEqual(['p', 'e', 's'])
    expect(toWord('piesok')).toEqual(['p', 'ie', 's', 'o', 'k'])
    expect(toWord('pije')).toEqual(['p', 'i', 'j', 'e'])
    expect(toWord('píše')).toEqual(['p', 'í', 'š', 'e'])
    expect(toWord('pyžamo')).toEqual(['p', 'i', 'ž', 'a', 'm', 'o'])
    expect(toWord('bába')).toEqual(['b', 'á', 'b', 'a'])
    expect(toWord('bager')).toEqual(['b', 'a', 'g', 'e', 'r'])
    expect(toWord('balón')).toEqual(['b', 'a', 'l', 'ó', 'n'])
    expect(toWord('bocian')).toEqual(['b', 'o', 'c', 'ia', 'n'])
    expect(toWord('mama')).toEqual(['m', 'a', 'm', 'a'])
    expect(toWord('maco')).toEqual(['m', 'a', 'c', 'o'])
    expect(toWord('motýľ')).toEqual(['m', 'o', 't', 'í', 'ľ'])
    expect(toWord('mucha')).toEqual(['m', 'u', 'ch', 'a'])
    expect(toWord('topí')).toEqual(['t', 'o', 'p', 'í'])
    expect(toWord('tuleň')).toEqual(['t', 'u', 'l', 'e', 'ň'])
    expect(toWord('deka')).toEqual(['d', 'e', 'k', 'a'])
    expect(toWord('dom')).toEqual(['d', 'o', 'm'])
    expect(toWord('dúha')).toEqual(['d', 'ú', 'h', 'a'])
    expect(toWord('dym')).toEqual(['d', 'i', 'm'])
    expect(toWord('noha')).toEqual(['n', 'o', 'h', 'a'])
    expect(toWord('nos')).toEqual(['n', 'o', 's'])
    expect(toWord('váza')).toEqual(['v', 'á', 'z', 'a'])
    expect(toWord('voda')).toEqual(['v', 'o', 'd', 'a'])
    expect(toWord('fotí')).toEqual(['f', 'o', 'ť', 'í'])
    expect(toWord('fúka')).toEqual(['f', 'ú', 'k', 'a'])
    expect(toWord('kečup')).toEqual(['k', 'e', 'č', 'u', 'p'])
    expect(toWord('kohút')).toEqual(['k', 'o', 'h', 'ú', 't'])
    expect(toWord('kone')).toEqual(['k', 'o', 'ň', 'e'])
    expect(toWord('kolotoč')).toEqual(['k', 'o', 'l', 'o', 't', 'o', 'č'])
    expect(toWord('kôš')).toEqual(['k', 'ô', 'š'])
    expect(toWord('gombík')).toEqual(['g', 'o', 'm', 'b', 'í', 'k'])
    expect(toWord('guľa')).toEqual(['g', 'u', 'ľ', 'a'])
    expect(toWord('had')).toEqual(['h', 'a', 't'])
    expect(toWord('hodiny')).toEqual(['h', 'o', 'ď', 'i', 'n', 'i'])
    expect(toWord('hus')).toEqual(['h', 'u', 's'])
    expect(toWord('husenica')).toEqual(['h', 'u', 's', 'e', 'ň', 'i', 'c', 'a'])
    expect(toWord('hádže')).toEqual(['h', 'á', 'dž', 'e'])
    expect(toWord('chata')).toEqual(['ch', 'a', 't', 'a'])
    expect(toWord('chobot')).toEqual(['ch', 'o', 'b', 'o', 't'])
    expect(toWord('chlapec')).toEqual(['ch', 'l', 'a', 'p', 'e', 'c'])
    expect(toWord('chvost')).toEqual(['ch', 'v', 'o', 's', 't'])
    expect(toWord('jahoda')).toEqual(['j', 'a', 'h', 'o', 'd', 'a'])
    expect(toWord('jazyk')).toEqual(['j', 'a', 'z', 'i', 'k'])
    expect(toWord('jeden')).toEqual(['j', 'e', 'ď', 'e', 'n'])
    expect(toWord('ťava')).toEqual(['ť', 'a', 'v', 'a'])
    expect(toWord('deti')).toEqual(['ď', 'e', 'ť', 'i'])
    expect(toWord('dievča')).toEqual(['d', 'ie', 'f', 'č', 'a'])
    expect(toWord('ňufák')).toEqual(['ň', 'u', 'f', 'á', 'k'])
    expect(toWord('nite')).toEqual(['ň', 'i', 'ť', 'e'])
    expect(toWord('sedí')).toEqual(['s', 'e', 'ď', 'í'])
    expect(toWord('sanitka')).toEqual(['s', 'a', 'ň', 'i', 't', 'k', 'a'])
    expect(toWord('stĺp')).toEqual(['s', 't', 'ĺ', 'p'])
    expect(toWord('stôl')).toEqual(['s', 't', 'ô', 'l'])
    expect(toWord('sukňa')).toEqual(['s', 'u', 'k', 'ň', 'a'])
    expect(toWord('zelená')).toEqual(['z', 'e', 'l', 'e', 'n', 'á'])
    expect(toWord('zemiaky')).toEqual(['z', 'e', 'm', 'ia', 'k', 'i'])
    expect(toWord('zuby')).toEqual(['z', 'u', 'b', 'i'])
    expect(toWord('cibuľa')).toEqual(['c', 'i', 'b', 'u', 'ľ', 'a'])
    expect(toWord('šál')).toEqual(['š', 'á', 'l'])
    expect(toWord('šupka')).toEqual(['š', 'u', 'p', 'k', 'a'])
    expect(toWord('žaba')).toEqual(['ž', 'a', 'b', 'a'])
    expect(toWord('žirafa')).toEqual(['ž', 'i', 'r', 'a', 'f', 'a'])
    expect(toWord('čaj')).toEqual(['č', 'a', 'j'])
    expect(toWord('číta')).toEqual(['č', 'í', 't', 'a'])
    expect(toWord('čiapka')).toEqual(['č', 'ia', 'p', 'k', 'a'])
    expect(toWord('čokoláda')).toEqual(['č', 'o', 'k', 'o', 'l', 'á', 'd', 'a'])
    expect(toWord('lampa')).toEqual(['l', 'a', 'm', 'p', 'a'])
    expect(toWord('loď')).toEqual(['l', 'o', 'ť'])
    expect(toWord('leží')).toEqual(['l', 'e', 'ž', 'í'])
    expect(toWord('lienka')).toEqual(['l', 'ie', 'n', 'k', 'a'])
    expect(toWord('kladivo')).toEqual(['k', 'l', 'a', 'ď', 'i', 'v', 'o'])
    expect(toWord('ruka')).toEqual(['r', 'u', 'k', 'a'])
    expect(toWord('ruža')).toEqual(['r', 'u', 'ž', 'a'])
    expect(toWord('ryba')).toEqual(['r', 'i', 'b', 'a'])
    expect(toWord('vŕba')).toEqual(['v', 'ŕ', 'b', 'a'])
    expect(toWord('vŕta')).toEqual(['v', 'ŕ', 't', 'a'])
    expect(toWord('oko')).toEqual(['o', 'k', 'o'])
    expect(toWord('opica')).toEqual(['o', 'p', 'i', 'c', 'a'])
    expect(toWord('orech')).toEqual(['o', 'r', 'e', 'ch'])
    expect(toWord('ucho')).toEqual(['u', 'ch', 'o'])
    expect(toWord('umýva')).toEqual(['u', 'm', 'í', 'v', 'a'])
    expect(toWord('uši')).toEqual(['u', 'š', 'i'])

  })
})